---
os: linux
dist:
  - xenial
  - bionic
  - focal

language: generic

# env:
#   matrix:
#     - TEST_SUITE='default'
#
# jobs:
#   include:
#     - os: osx
#       osx_image: xcode12
#       env: TEST_USER_HOME_DIR_BASE='/Users'
#     - os: osx
#       osx_image: xcode11.2
#       env: TEST_USER_HOME_DIR_BASE='/Users'

sudo: required
env:
  global:
    - TEST_ANSIBLE_HOSTNAME: localhost
      TEST_ANSIBLE_CONNECTION: local
      TEST_USER_HOME_DIR_BASE: '/home'
      PYTHON: 3.6.7
      ANSIBLE_BECOME_PASS: travis
install:
  - pip3 install --upgrade pip
  - pip3 install ansible ansible-lint
script:
  - ansible-lint .
  - ansible-playbook -i test/inventory test/playbook.yml --syntax-check
  - ansible-playbook -i test/inventory test/playbook.yml --list-tasks
  - ansible-playbook -i test/inventory test/playbook.yml --connection=local -vvvv
  - ansible-playbook -i test/inventory test/playbook.yml --connection=local -vvvv
  - 'ansible-playbook -i test/inventory test/playbook.yml --connection=local | grep -q "changed=0.*failed=0" &&
    (echo "Idempotence test: pass" && exit 0) || (echo "Idempotence test: fail" && exit 1)'

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
